title: The Cox Group
description: A computational and theoretical chemistry group in the Department of Chemistry, Durham University.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
url: https://CoxGroup.github.io
baseurl: "/CoxGroup"
